
# Constants as defined by the AST library.
# This file is incomplete and TOTALLY subject to change.

SYSTEM_ECLIPTIC = "Ecliptic"
SYSTEM_EQUATORIAL = "EQUATORIAL" # same as FK5
SYSTEM_FK5 = "FK5"
SYSTEM_GALACTIC = "Galactic"
SYSTEM_HORIZON = "AZEL"
SYSTEM_FK4_BARYOCENTRIC = "FK4-NO-E"
SYSTEM_GEOCENTRIC_APPARENT_EQUATORIAL = "GEOCENTRIC"
SYSTEM_HELIOECLIPTIC = "HELIOECLIPTIC"
SYSTEM_ICRS = "ICRS"
SYSTEM_J2000 = "J2000"
SYSTEM_SUPERGALACTIC = "Supergalactic"
SYSTEM_UNKNOWN = "UNKNOWN"

# SpecFrame "System" values
SYSTEM_FREQUENCY_GHZ = "FREQ"
SYSTEM_ENERGY_J = "ENER"
SYSTEM_WAVENUMBER = "WAVENUMBER"
SYSTEM_VACUUM_WAVELENGTH = "WAVELEN"
SYSTEM_AIR_WAVELENGTH = "AIRWAVE"
SYSTEM_RADIO_VELOCITY = "VRADIO"
SYSTEM_OPTICAL_VELOCITY = "VOPTICAL"
SYSTEM_REDSHIFT = "REDSHIFT"
SYSTEM_BETA_FACTOR = "BETA"
SYSTEM_APPARENT_RADIAL = "VREL"

# The TimeFrame class supports these systems
SYSTEM_MJD = "MJD"
SYSTEM_JULIAN_DATE = "JD"
SYSTEM_JULIAN_EPOCH = "JEPOCH"
SYSTEM_BESSELIAN = "BEOPCH"

EQUINOX_J2000 = "J2000"
EQUINOX_J2010 = "J2010"
EQUINOX_2001 = "2001"

AST_SURFACE_MESH = 0
AST_BOUNDARY_MESH = 1

